<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SRINIVAS-G2005" failures="4" tests="10" name="Test" time="24.082" errors="0" timestamp="2025-04-18T11:57:35 IST">
  <testcase classname="api.test.User_DDTests" name="testPostUser" time="3.881"/>
  <testcase classname="api.test.User_DDTests" name="testPostUser" time="2.17"/>
  <testcase classname="api.test.User_DDTests" name="testPostUser" time="1.918"/>
  <testcase classname="api.test.User_DDTests" name="testDeleteUserByName" time="2.12">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.User_DDTests.testDeleteUserByName(User_DDTests.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.User_DDTests" name="testDeleteUserByName" time="1.699">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.User_DDTests.testDeleteUserByName(User_DDTests.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.User_DDTests" name="testDeleteUserByName" time="1.734"/>
  <testcase classname="api.test.UserTests" name="testPostUser" time="1.672"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="1.89">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testGetUserByName(UserTests.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="3.838">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testUpdateUserByName(UserTests.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUserByName -->
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.918"/>
</testsuite> <!-- Test -->
